services:
  backend:
    build: ./backend
    container_name: login-backend
    depends_on:
      - frontend
    ports:
      - 5000:5000

    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_NAME: login_app
      DB_PASSWORD:

  frontend:
    build: ./frontend
    container_name: login-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend