services:
  mysql:
    image: mysql:8.0
    container_name: login-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: login_app
      MYSQL_ROOT_PASSWORD: rootpassword

    ports:
    - "3307:3306"

    volumes:
    - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: login-backend
    depends_on:
      - mysql
    ports:
      - 5000:5000

    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_NAME: login_app
      DB_PASSWORD: rootpassword

  frontend:
    build: ./frontend
    container_name: login-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql_data: